import { Router } from 'express';
import { auth, requireRole } from '../middleware/auth';
import * as A from '../controllers/auth';
import * as P from '../controllers/providers';
import * as S from '../controllers/services';
import * as B from '../controllers/bookings';
import * as M from '../controllers/misc';
const r = Router(); const prov = [auth, requireRole('provider')]; const cust = [auth, requireRole('customer')]; const admin = [auth, requireRole('admin')];
r.post('/auth/register', A.register); r.post('/auth/login', A.login); r.post('/auth/logout', (_q, s) => { s.json({ ok: true }); }); r.get('/auth/me', auth, A.me);
r.get('/providers/nearby', P.nearby); r.get('/providers/me', ...prov, P.mine); r.patch('/providers/me', ...prov, P.updateMine);
r.get('/providers/:id', P.getOne); r.get('/providers/:id/slots', P.slots); r.get('/providers/:id/reviews', P.reviews);
r.get('/services', ...prov, S.list); r.post('/services', ...prov, S.create); r.patch('/services/:id', ...prov, S.update); r.delete('/services/:id', ...prov, S.remove);
r.post('/bookings', ...cust, B.create); r.get('/bookings', auth, B.list); r.get('/bookings/:id', auth, B.getOne);
r.patch('/bookings/:id/status', ...prov, B.setStatus); r.post('/bookings/:id/cancel', ...cust, B.cancel);
r.post('/reviews', ...cust, M.createReview);
r.get('/conversations', auth, M.conversations); r.get('/conversations/:userId/messages', auth, M.messages);
r.get('/notifications', auth, M.notifications); r.post('/notifications/read-all', auth, M.readAll);
r.get('/admin/stats', ...admin, M.adminStats); r.patch('/admin/providers/:id/verify', ...admin, M.verifyProvider); r.patch('/admin/users/:id/suspend', ...admin, M.suspendUser);
export default r;
